spring.application.name=internalfintech

server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/demo
spring.datasource.username=admin
spring.datasource.password=1234567
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect